#!/bin/bash
# Auto-generate documentation manifest from markdown files
# Usage: ./scripts/generate-doc-manifest.sh

DOCS_DIR="frontend/src/assets/docs"
MANIFEST_FILE="$DOCS_DIR/manifest.json"

# Icon mapping for common doc types
declare -A ICONS=(
    ["OVERVIEW"]="📖"
    ["QUICKSTART"]="🚀"
    ["INSTALL"]="📥"
    ["ARCHITECTURE"]="🏗️"
    ["STRUCTURE"]="📁"
    ["PROJECT_STRUCTURE"]="📁"
    ["DEMOS"]="🎯"
    ["API"]="🔌"
    ["CHANGELOG"]="📋"
    ["GUIDE"]="📚"
    ["TUTORIAL"]="🎓"
    ["FAQ"]="❓"
    ["TROUBLESHOOTING"]="🔧"
    ["SECURITY"]="🔒"
    ["CONTRIBUTING"]="🤝"
)

# Default icon
DEFAULT_ICON="📄"

# Start JSON
echo '{' > "$MANIFEST_FILE"
echo '  "documentation": [' >> "$MANIFEST_FILE"

# Counter for ordering
order=1
first=true

# Find all .md files (excluding manifest.json)
for file in "$DOCS_DIR"/*.md; do
    # Skip if no files found
    [ -e "$file" ] || continue
    
    # Get filename without path and extension
    filename=$(basename "$file" .md)
    
    # Skip manifest itself
    [ "$filename" = "manifest" ] && continue
    
    # Get icon from mapping or use default
    icon="${ICONS[$filename]:-$DEFAULT_ICON}"
    
    # Add comma before all but first entry
    if [ "$first" = true ]; then
        first=false
    else
        echo ',' >> "$MANIFEST_FILE"
    fi
    
    # Write JSON entry
    cat >> "$MANIFEST_FILE" << EOF
    {
      "id": "$filename",
      "label": "$(echo "$filename" | sed 's/_/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')",
      "icon": "$icon",
      "file": "$filename.md",
      "order": $order
    }
EOF
    
    ((order++))
done

# Close JSON
echo '' >> "$MANIFEST_FILE"
echo '  ],' >> "$MANIFEST_FILE"
echo '  "metadata": {' >> "$MANIFEST_FILE"
echo '    "basePath": "assets/docs/",' >> "$MANIFEST_FILE"
echo '    "autoGenerated": true,' >> "$MANIFEST_FILE"
echo "    \"lastUpdated\": \"$(date -Iseconds)\"" >> "$MANIFEST_FILE"
echo '  }' >> "$MANIFEST_FILE"
echo '}' >> "$MANIFEST_FILE"

echo "✓ Generated manifest with $((order-1)) documentation items"
echo "  Location: $MANIFEST_FILE"
