/**
 * Documentation Service
 * 
 * Dynamically loads documentation manifest and provides menu items
 * 
 * Usage:
 * ```typescript
 * const docService = inject(DocService);
 * await docService.loadManifest();
 * const items = docService.getDocItems();
 * ```
 */

import { Injectable, inject, signal, computed } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { LoggerService } from './logger.service';

export interface DocManifest {
  documentation: DocItem[];
  metadata: {
    basePath: string;
    autoGenerated: boolean;
    lastUpdated: string;
  };
}

export interface DocItem {
  id: string;
  label: string;
  icon: string;
  file: string;
  order: number;
}

@Injectable({ providedIn: 'root' })
export class DocService {
  private readonly http = inject(HttpClient);
  private readonly logger = inject(LoggerService);

  private readonly manifest = signal<DocManifest | null>(null);
  private readonly loaded = signal(false);
  private readonly loading = signal(false);
  private readonly error = signal<string | null>(null);

  readonly manifest$ = this.manifest.asReadonly();
  readonly isLoading$ = this.loading.asReadonly();
  readonly isLoaded$ = this.loaded.asReadonly();
  readonly error$ = this.error.asReadonly();

  readonly docItems = computed(() => {
    const manifest = this.manifest();
    if (!manifest) return [];
    
    return manifest.documentation
      .slice()
      .sort((a, b) => a.order - b.order)
      .map(item => ({
        id: item.id,
        label: item.label,
        icon: item.icon,
        active: false
      }));
  });

  readonly basePath = computed(() => {
    return this.manifest()?.metadata?.basePath || 'assets/docs/';
  });

  async loadManifest(): Promise<void> {
    if (this.loaded() || this.loading()) {
      return;
    }

    this.loading.set(true);
    this.error.set(null);

    return new Promise<void>((resolve, reject) => {
      this.http.get<DocManifest>('assets/docs/manifest.json').subscribe({
        next: (manifest) => {
          this.manifest.set(manifest);
          this.loaded.set(true);
          this.loading.set(false);
          this.logger.info(`Documentation manifest loaded: ${manifest.documentation.length} items`);
          resolve();
        },
        error: (error) => {
          const message = error instanceof Error ? error.message : 'Failed to load manifest';
          this.error.set(message);
          this.loading.set(false);
          this.logger.error('Failed to load documentation manifest', error);
          
          // Load default items as fallback
          this.loadDefaultManifest();
          resolve(); // Resolve anyway to allow app to continue
        }
      });
    });
  }

  private loadDefaultManifest(): void {
    const defaultManifest: DocManifest = {
      documentation: [
        { id: 'OVERVIEW', label: 'Overview', icon: '📖', file: 'OVERVIEW.md', order: 1 },
        { id: 'QUICKSTART', label: 'Quick Start', icon: '🚀', file: 'QUICKSTART.md', order: 2 },
        { id: 'ARCHITECTURE', label: 'Architecture', icon: '🏗️', file: 'ARCHITECTURE.md', order: 3 },
      ],
      metadata: {
        basePath: 'assets/docs/',
        autoGenerated: true,
        lastUpdated: new Date().toISOString()
      }
    };
    this.manifest.set(defaultManifest);
    this.loaded.set(true);
  }

  getDocItems(): DocItem[] {
    const manifest = this.manifest();
    if (!manifest) return [];
    
    return manifest.documentation
      .slice()
      .sort((a, b) => a.order - b.order);
  }

  getDocItem(id: string): DocItem | undefined {
    const manifest = this.manifest();
    if (!manifest) return undefined;
    
    return manifest.documentation.find(item => item.id === id);
  }

  getDocPath(id: string): string | null {
    const item = this.getDocItem(id);
    if (!item) return null;
    
    return `${this.basePath()}${item.file}`;
  }

  async reloadManifest(): Promise<void> {
    this.loaded.set(false);
    this.manifest.set(null);
    await this.loadManifest();
  }
}
